=== heintzboerje/Site_techno_web/SITE_Niang_Polo/XML/horror.dtd
<!ELEMENT film (title, poster?, director+, infos, cast, synopsis, more?)>
<!ATTLIST film
        id ID #REQUIRED
        trailer CDATA #IMPLIED>

<!ELEMENT title (#PCDATA)>

<!ELEMENT poster EMPTY>
<!ATTLIST poster
        src CDATA #REQUIRED
        alt CDATA #REQUIRED>

<!ELEMENT synopsis (#PCDATA)>

<!ELEMENT director (firstname, lastname?)>
<!ATTLIST director 
        id ID #REQUIRED>

<!ELEMENT firstname (#PCDATA)>
<!ELEMENT lastname (#PCDATA)>

<!ELEMENT infos (release, languages)>

<!ELEMENT release (#PCDATA)>

<!ELEMENT languages (language+)>
<!ELEMENT language (#PCDATA)>

<!ELEMENT cast (actor+)>

<!ELEMENT actor (firstname, lastname, roles)>

<!ELEMENT roles (character+)>

<!ELEMENT character (#PCDATA)>

<!ELEMENT more (significance, anecdote*)>

<!ELEMENT significance (#PCDATA)>
<!ELEMENT anecdote (#PCDATA)>

=== heintzboerje/Site_techno_web/SITE_Niang_Polo/XML/scream.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="movie_styles.css"?>
<!DOCTYPE film SYSTEM "horror.dtd">
<film id="scream" trailer="">
    <title>Scream</title>
    <poster src="scream.jpg" alt="Affiche du Film"/>
    <director id="craven">
        <firstname>Wes</firstname>
        <lastname>Craven</lastname>
    </director>
    <infos>
        <release>20 décembre 1996</release>
        <languages>
            <language>anglais</language>
        </languages>
    </infos>
    <cast>
        <actor>
            <firstname>Neve</firstname>
            <lastname>Campbell</lastname>
            <roles>
                <character>Sidney Prescott, lycéenne cible principale du tueur</character>
            </roles>
        </actor>
        <actor>
            <firstname>Courteney</firstname>
            <lastname>Cox</lastname>
            <roles>
                <character>Gale Weathers, journaliste ambitieuse enquêtant sur les meurtres</character>
            </roles>
        </actor>
        <actor>
            <firstname>David</firstname>
            <lastname>Arquette</lastname>
            <roles>
                <character>Dewey Riley, adjoint du shérif et frère de Tatum</character>
            </roles>
        </actor>
        <actor>
            <firstname>Drew</firstname>
            <lastname>Barrymore</lastname>
            <roles>
                <character>Casey Backer, première victime du tueur</character>
            </roles>
        </actor>
    </cast>
    <synopsis>
        Ce film de 1996 suit un mystérieux tueur en série, surnommé Ghostface,
        qui terrorise une petite ville californienne en s'inspirant des classiques du cinéma d'horreur.
        Le film est reconnu pour avoir revitalisé le genre du slasher dans les années 1990.
    </synopsis>
    <more>
        <significance>Revitalisation du genre slasher dans les années 1990</significance>
        <anecdote>
            Lors du tournage, Drew Barrymore devait initialement jouer l'héroïne principale,
            mais a demandé à incarner la première victime pour surprendre le public dès le début du film.
        </anecdote>
    </more>

</film>

=== heintzboerje/Site_techno_web/SITE_Niang_Polo/XML/shining.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="horror.xsl"?>
<!DOCTYPE film SYSTEM "horror.dtd">
<film id="the_shining" trailer="https://youtu.be/JkZzWDaId-s">
        <title>The Shining</title>
        <poster src="https://upload.wikimedia.org/wikipedia/en/1/1d/The_Shining_%281980%29_U.K._release_poster_-_The_tide_of_terror_that_swept_America_IS_HERE.jpg" alt="Pas de poster disponible pour ce film"/>
        <director id="kubrick">
                <firstname>Stanley</firstname>
                <lastname>Kubrick</lastname>
        </director>
        <infos>
                <release>1980</release>
                <languages>
                        <language>english</language>
                </languages>
        </infos>
        <cast>
                <actor>
                        <firstname>Jack</firstname>
                        <lastname>Nicholson</lastname>
                        <roles>
                                <character>Jack Torrance</character>
                        </roles>
                </actor>
                <actor>
                        <firstname>Danny</firstname>
                        <lastname>Lloyd</lastname>
                        <roles>
                                <character>Danny Torrance</character>
                        </roles>
                </actor>
        </cast>
        <synopsis>
                Un écrivain alcoolique est engagé comme gardien d'un grand hotel isolé dans le Colorado.
                Il y déménage avec sa famille et son fils possédant le talent de médium est de plus en plus hanté par
                des visions de meutres déroulé à l'hotel.
        </synopsis>
        <more>
                <significance> TEST </significance>
                <anecdote> funny stuff </anecdote>
        </more>
</film>

=== heintzboerje/Site_techno_web/SITE_Niang_Polo/XML/bring_her_back.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="horror.xsl"?>
<!DOCTYPE film SYSTEM "horror.dtd">
<film id="bring_her_back" trailer="https://www.youtube.com/watch?v=RsKygtA2DMY%26pp=ygUOYnJpbmcgaGVyIGJhY2s%3D">
        <title>Bring her back</title>
        <poster src="https://upload.wikimedia.org/wikipedia/en/f/fd/Bring_Her_Back_film_poster.jpg" alt="Pas de poster disponible pour ce film"/>
        <director id="danny">
                <firstname>Danny</firstname>
                <lastname>Philippou</lastname>
        </director>
        <director id="michael">
                <firstname>Michael</firstname>
                <lastname>Philippou</lastname>
        </director>
        <infos>
                <release>30 mai 2025</release>
                <languages>
                        <language>english</language>
                </languages>
        </infos>
        <cast>
                <actor>
                        <firstname>Sally</firstname>
                        <lastname>Hawkins</lastname>
                        <roles>
                                <character>Non connu</character>
                        </roles>
                </actor>
                <actor>
                        <firstname>Billy</firstname>
                        <lastname>Barratt</lastname>
                        <role>
                                <character>Non connu</character>
                        </role>
                </actor>
        </cast>
        <synopsis>Une fratrie d√©couvre un rituel terrifiant chez leur nouvelle famille d'accueil.'</synopsis>
</film>

=== heintzboerje/Site_techno_web/SITE_Niang_Polo/XML/blair_witch_project.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="horror.xsl"?>
<!DOCTYPE film SYSTEM "horror.dtd">
<film id="blair_witch_project" trailer="">
        <title>The Blair Witch Project</title>
        <poster src="https://poster"/>
        <director id="myrick">
                <firstname>Daniel</firstname>
                <lastname>Myrick</lastname>
        </director>
        <director id="sanchez">
                <firstname>Eduardo</firstname>
                <lastname>Sanchez</lastname>
        </director>
        <infos>
                <release>30 Juillet 1999</release>
                <languages>
                        <language>english</language>
                </languages>
        </infos>
        <cast>
                <actor>
                        <firstname>Heather</firstname>
                        <lastname>Donahue</lastname>
                        <roles>
                                <character>Heather Donahue</character>
                        </roles>
                </actor>
                <actor>
                        <firstname>Joshua</firstname>
                        <lastname>Leonard</lastname>
                        <roles>
                                <character>Joshua Leonard</character>
                        </roles>
                </actor>
                <actor>
                        <firstname>Michael</firstname>
                        <lastname>Williams</lastname>
                        <roles>
                                <character>Michael Williams</character>
                        </roles>
                </actor>
        </cast>
        <synopsis>
                Trois étudiants investiguent la légende de Blair Witch, dans le Maryland
                disparaissent en ne laissant derrière eux que l'enregistrement de leur investiguation.
        </synopsis>
        <more>
                <significance>It had great impact</significance>
                <anecdote>Il y une scene où les acteurs dorment dans une tente.
                        La tente est soudainement violemment secoué et ils se 
                        réveillent paniqués. Cette scène n'était pas scripté.
                        Les réalisateur ont secoué la tente et les acteurs était
                        réellement paniqués.
                </anecdote>
        </more> 
</film>

=== heintzboerje/Site_techno_web/SITE_Niang_Polo/XML/the_exorcist.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="movie_styles.css"?>
<!DOCTYPE film SYSTEM "horror.dtd">
<film id="the_exorcist" trailer="">
    <title>The Exorcist</title>
    <poster src="the_exorcist.jpeg" alt="Affiche du Film"/>
    <director id="friedkin">
        <firstname>William</firstname>
        <lastname>Friedkin</lastname>
    </director>
    <infos>
        <release>26 décembre 1973</release>
        <languages>
            <language>anglais</language>
        </languages>
    </infos>
    <cast>
        <actor>
            <firstname>Linda</firstname>
            <lastname>Blair</lastname>
            <roles>
                <character>Regan MacNeil, la jeune fille possédée, dont le comportement devient de plus en plus effrayant et incontrôlable.</character>
            </roles>
        </actor>
        <actor>
            <firstname>Max</firstname>
            <lastname>von Sydow</lastname>
            <roles>
                <character>Père Lankester Merrin, prêtre expérimenté qui revient pour réaliser l'exorcisme de Regan.</character>
            </roles>
        </actor>
        <actor>
            <firstname>Jason</firstname>
            <lastname>Miller</lastname>
            <roles>
                <character>Père Damien Karras, prêtre et psychiatre, en proie au doute, qui assiste au rite de l'exorcisme</character>
            </roles>
        </actor>
        <actor>
            <firstname>Ellen</firstname>
            <lastname>Burstyn</lastname>
            <roles>
                <character>Chris MacNeil, la mère de Regan, actrice célèbre qui cherche une solution quand sa fille commence à se comporter de manière étrange.</character>
            </roles>
        </actor>
    </cast>
    <synopsis>
        Sorti en 1973, ce film raconte l'histoire de Regan MacNeil, une jeune fille possédée par un démon,
        et des prêtres qui tentent de l'exorciser. Inspiré d'un véritable cas d'exorcisme en 1949, il est considéré comme un classique du cinéma d'horreur.
    </synopsis>
    <more>
        <significance>Considéré comme l'un des films d'horreur les plus influents de l'histoire du cinéma</significance>
        <anecdote>
            Lors du tournage, la température sur le plateau était maintenue très basse pour que les acteurs puissent
            réellement voir leur souffle à l'écran, créant ainsi une atmosphère glaciale authentique.
        </anecdote>
    </more>

</film>
